This notebook creates the Google search queries for each Local Education Agency (LEA) to get its BoardDocs website.

Input:
- `../nces2324.csv`

Output:
- `lea_boarddocs_queries.csv`

In [10]:
import pandas as pd

df = pd.read_csv("../nces2324.csv")

/var/folders/cp/kz443md17ndf52c8_802gy080000gn/T/ipykernel_35160/832504288.py:3: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../nces2324.csv")

In [11]:
# the query should be its name
df['query'] = df['LEA_NAME']

In [12]:
df['query'].duplicated(keep=False).sum()

np.int64(654)

In [13]:
# for duplicated ones, we add in the zip code
# we don't do it for all queries because some school don't put their addresses on the boarddocs website

df.loc[df['query'].duplicated(keep=False), 'query'] = df['LEA_NAME'] + ' ' + df['LZIP'].astype(str)

In [14]:
sum(df['query'].duplicated(keep=False))

17

In [15]:
df.loc[df['query'].duplicated(keep=False)].sort_values(by="query")

,SCHOOL_YEAR,FIPST,STATENAME,ST,LEA_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,MSTREET1,...,G_12_OFFERED,G_13_OFFERED,G_UG_OFFERED,G_AE_OFFERED,GSLO,GSHI,LEVEL,IGOFFERED,OPERATIONAL_SCHOOLS,query
2366,2023-2024,6,CALIFORNIA,CA,Excel Academy Charter District,1,NaN,CA-0139576,602487,1 Tech Dr.,...,Yes,No,No,No,KG,12,Other,As reported,1,Excel Academy Charter District 92618
2376,2023-2024,6,CALIFORNIA,CA,Excel Academy Charter District,1,NaN,CA-0139386,602500,1 Tech Dr.,...,Yes,No,No,No,KG,12,Other,As reported,1,Excel Academy Charter District 92618
3979,2023-2024,12,FLORIDA,FL,IDEA PUBLIC SCHOOLS,1,NaN,FL-80,1200084,2115 W. Pike Blvd,...,Yes,No,No,No,KG,12,Other,As reported,4,IDEA PUBLIC SCHOOLS 78596
16824,2023-2024,48,TEXAS,TX,IDEA PUBLIC SCHOOLS,1,NaN,TX-108807,4800211,2115 W PIKE BLVD,...,Yes,No,No,No,KG,12,Other,As reported,123,IDEA PUBLIC SCHOOLS 78596
14659,2023-2024,40,OKLAHOMA,OK,INDIAN CAPITAL TECHNOLOGY CTR,1,NaN,OK-68-V004,4000089,HC 61 BOX 12,...,No,No,No,No,N,N,Not applicable,As reported,0,INDIAN CAPITAL TECHNOLOGY CTR 74403
14619,2023-2024,40,OKLAHOMA,OK,INDIAN CAPITAL TECHNOLOGY CTR,1,NaN,OK-01-V004,4000047,RR 6 BOX 3320,...,No,No,No,No,N,N,Not applicable,As reported,0,INDIAN CAPITAL TECHNOLOGY CTR 74403
14648,2023-2024,40,OKLAHOMA,OK,INDIAN CAPITAL TECHNOLOGY CTR,1,NaN,OK-51-V004,4000077,2403 N 41ST ST E,...,No,No,No,No,N,N,Not applicable,As reported,0,INDIAN CAPITAL TECHNOLOGY CTR 74403
6905,2023-2024,22,LOUISIANA,LA,Mildred Osborne Charter School,1,NaN,LA-WV2,2200249,6701 Curran Blvd,...,Not reported,Not reported,Not reported,Not reported,M,M,Not reported,As reported,0,Mildred Osborne Charter School 70126
7034,2023-2024,22,LOUISIANA,LA,Mildred Osborne Charter School,1,NaN,LA-WZS,2280106,6701 Curran Blvd.,...,No,No,No,No,PK,08,Elementary,As reported,1,Mildred Osborne Charter School 70126
1410,2023-2024,6,CALIFORNIA,CA,Mission Valley ROC/P,1,NaN,CA-0140402,601397,5019 Stevenson Blvd.,...,No,No,No,No,N,N,Not applicable,As reported,0,Mission Valley ROC/P 94538
1305,2023-2024,6,CALIFORNIA,CA,Mission Valley ROC/P,1,NaN,CA-0174021,600086,5019 Stevenson Blvd.,...,Yes,No,No,No,09,12,High,As reported,1,Mission Valley ROC/P 94538
1387,2023-2024,6,CALIFORNIA,CA,San Antonio ROP,1,NaN,CA-1940691,601367,605 North Park Ave.,...,No,No,No,No,N,N,Not applicable,As reported,0,San Antonio ROP 91768
1327,2023-2024,6,CALIFORNIA,CA,San Antonio ROP,1,NaN,CA-1974849,600114,605 North Park Ave.,...,Yes,No,No,No,KG,12,Other,As reported,1,San Antonio ROP 91768
1378,2023-2024,6,CALIFORNIA,CA,San Gabriel Valley Regional Occupational Program,1,NaN,CA-1940154,601356,1134 South Barranca Ave.,...,No,No,No,No,N,N,Not applicable,As reported,0,San Gabriel Valley Regional Occupational Progr...
1318,2023-2024,6,CALIFORNIA,CA,San Gabriel Valley Regional Occupational Program,1,NaN,CA-1974195,600105,1134 South Barranca Ave.,...,Yes,No,No,No,09,12,High,As reported,1,San Gabriel Valley Regional Occupational Progr...
1370,2023-2024,6,CALIFORNIA,CA,Tri-Cities ROP,1,NaN,CA-1940162,601346,10800 Ben Avon St.,...,No,No,No,No,N,N,Not applicable,As reported,0,Tri-Cities ROP 90606
1319,2023-2024,6,CALIFORNIA,CA,Tri-Cities ROP,1,NaN,CA-1974328,600106,10800 Ben Avon St. Unit E,...,Yes,No,No,No,09,12,High,As reported,1,Tri-Cities ROP 90606

In [16]:
# turns out that all 17 duplicated rows have the same zip code too.
# just give the same query, it's fine
# don't include zip code
df['query'] = df['LEA_NAME']

In [17]:
# select cols
df = df[["LEA_NAME", "LEAID", "STATENAME"]]
df.to_csv("lea_boarddocs_queries.csv", index=False)